### PR TITLE
fix permission issue on script

### LINKED ISSUE #56: Problem: Terraform Permission Issue
Got this error while doing `terraform apply`

Screenshot from 2022-08-07 15-47-13

### PR DESCRIPTION
**Pull request by bafread**
This PR will
- close #56 
- fix #56 

Run `terraform apply`

### CODE REVIEW

File: terraform/scripts/restart_dockerd_with_tls.sh [hunk 1]
```diff
@@ -5,20 +5,20 @@ export DEBIAN_FRONTEND=noninteractive
 # Make docker daemon only accept connections with trusted certificate
 
 TARGET_DIR=/lib/systemd/system/docker.service.d
-mkdir -p "$TARGET_DIR"
+sudo mkdir -p "$TARGET_DIR"
 
 # override default ExecStart
-cat > "$TARGET_DIR/local.conf" << EOF
+sudo bash -c 'cat << EOF > $TARGET_DIR/local.conf
```
Comment (paseaf) [inline terraform/scripts/restart_dockerd_with_tls.sh:11]: `shellcheck restart_docker_with_tls.sh`
 returns the following error:
>   SC1004: This backslash+linefeed is literal. Break outside single quotes if you just want to break the line.

maybe use double quotes
```suggestion
sudo bash -c "cat << EOF > $TARGET_DIR/local.conf
```

File: terraform/scripts/restart_dockerd_with_tls.sh [hunk 2]
```diff
@@ -5,20 +5,20 @@ export DEBIAN_FRONTEND=noninteractive
...
 [Service]
 ExecStart=
 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock \
   --tlsverify --tlscacert=/home/deployer/ca.pem \
   --tlskey=/home/deployer/server-key.pem \
   --tlscert=/home/deployer/server-cert.pem \
   -H=0.0.0.0:2376
-EOF
+EOF'
```
Comment (paseaf) [inline terraform/scripts/restart_dockerd_with_tls.sh:19]:
```suggestion
EOF"
```

**Review by paseaf — CHANGES_REQUESTED** [review]
good catch! just one suggestion

**Review by paseaf — APPROVED** [review]
