### PR TITLE
Set up CA

### LINKED ISSUE #10: Flaky packer build
### Problem:
`packer build` sometimes failed with
```bash
==> logger-vm-image.googlecompute.ubuntu-2204: E: Could not open file /var/lib/apt/lists/esm.ubuntu.com_infra_ubuntu_dists_jammy-infra-updates_main_binary-amd64_Packages - open (2: No such file or directory)
==> logger-vm-image.googlecompute.ubuntu-2204: E: Could not open file /var/lib/apt/lists/esm.ubuntu.com_infra_ubuntu_dists_jammy-infra-security_main_binary-amd64_Packages - open (2: No such file or directory)
```
image

### Expected behavior
No such errors

### Current workaround:
just rerun the script

### LINKED ISSUE #15: Set up CA for sacrificial VM and gateway VM
> The next step involves creating a CA infrastructure so ContainerSSH can authenticate against the Docker daemon on the sacrificial host. This is described in the Docker manual.

- Detailed requirements: [Step 4: Creating certificates for authentication on the sacrificial host](https://containerssh.io/guides/honeypot/#step-4-creating-certificates-for-authentication-on-the-sacrificial-host)

### LINKED ISSUE #18: Error with Packer (before adding Expansion)
image

the strange error, come sometimes. I'll just ignore it for now and implement the other stuff for now, but would be cool if we could fix it, so it becomemore stabile. :)

### PR DESCRIPTION
**Pull request by bafread**
## Description
**This PR will**
- close #15 
- fix #10 and
- fix #18 with https://github.com/paseaf/containerSSH-honeypot/blob/be287d6c6fa6640fc3b049fa3ce0ee291697fc02/packer/main.pkr.hcl#L87

**Testing the PR**
You can verify the PR by following [`/terraform/README.md#Set-up-CA`](https://github.com/paseaf/containerSSH-honeypot/blob/another-version/terraform/README.md#2-set-up-ca) and set up the CA manually.

**Future improvements**
- #20 

**Developers notes**
- For CA's hostname, use `sacrificial-vm` (`$ hostname`) instead of `$ hostname -f`.
Reason: `$ hostname -f` is different for different GCP accounts, so we cannot hardcode the hostname, which makes the configuration more cumbersome.

#### Method 1: Create a docker context
- Term (Docker Context): a full environment for docker.

```bash
# create a context
docker context create --docker host=ssh://username@host remote-engine
# connect to the context
docker context use remote-engine
```
Now your `docker` will work directly on the remote host.

#### Method 2 (Our case): set `DOCKER_HOST`
Docker supports remote connection via SSH, TCP, TCP with TLS (our case)
```bash
export DOCKER_HOST=ssh://username@host remote-engine
```
This will directly send requests to the remote host using the current context.

## Q&A
Regarding [Container SSH documentation - Step 4](https://containerssh.io/guides/honeypot/#step-4-creating-certificates-for-authentication-on-the-sacrificial-host):
Answers from Janos:
### Q1: SSH vs. TLS
The document recommended us to connect to remote Docker engine over TLS. Why not over SSH? (SSH seems much easier to set up)
**A1:** SSH is unstable and should only be used for human access.
> Janos: SSH is an additional layer of complexity. You would need to keep the SSH tunnel alive all the time for this to work, which in practice doesn't really work all that well. I once ran an SSHFS mount for a longer period of time and it frequently crashed or became unresponsive since SSH is generally meant for human use. There are very few mechanisms to handle connection failures transparently.
> 
> [...] you need ContainerSSH to be able to connect to the remote Docker socket whenever a connection comes in. We have a limited set of retries for the initial connection and no retries afterwards. If the SSH tunnel breaks, the client gets disconnected. I can't precisely tell you why, but my experience is that using SSH for anything but human access is a bad idea.

### Q2: `docker run -H` doesn't work
The command on documentation doesn't work.
```bash
$ docker run -H tcp://your-sacrificial-host:2376 -ti ubuntu
unknown shorthand flag: 'H' in -H
See 'docker run --help'.
```
Is the command wrong? It works with
```bash
docker --tlsverify -H=tcp://sacrificial-vm:2376 run -ti ubuntu
```
when `~/.docker` is set up as [Docker - Secure by default](https://docs.docker.com/engine/security/protect-access/#secure-by-default)

**A2:** Janos: It should work with `docker -H <command>`
```bash
# GOOD 1
docker --tlsverify -H tcp://sacrificial-vm:2376 version

# GOOD 2 (with -H=)
docker --tlsverify -H=tcp://sacrificial-vm:2376 version

# GOOD 3
export TLSVERIFY=1
docker -H=tcp://sacrificial-vm:2376 version

# BAD
docker -H=tcp://sacrificial-vm:2376 version
> Error response from daemon: Client sent an HTTP request to an HTTPS server.
```
### Q3: Do we need Docker daemon to also run on port `2375`?
Step 4 gives two ports for Docker connection, but only `2376` seems to be used in other places in the doc. 
**A3:** Janos: typically `2376` for encrypted connection, `2375` for unencrypted.

Action: Our `2375` is not open. We can probably ignore it.
image

### CODE REVIEW

File: packer/scripts/update.sh [hunk 1]
```diff
@@ -39,5 +39,5 @@ apt-get -y update;
 echo "upgrade all installed packages incl. kernel and kernel headers"
 apt-get -y dist-upgrade -o Dpkg::Options::="--force-confnew";
 
-reboot
-
+sudo shutdown -r +1
+sleep 5m
```
[the remark this answers is not in the document]
Comment (bafread) [reply packer/scripts/update.sh:43]: it will fix the disconnected issue :)

File: terraform/main.tf [hunk 2]
```diff
@@ -23,41 +23,68 @@ resource "google_compute_subnetwork" "honeypot_subnet" {
   network       = google_compute_network.main.self_link
 }
 
-resource "google_compute_firewall" "allow_ssh_in" {
-  name    = "allow-ssh-in"
+# standard firewall settings
+resource "google_compute_firewall" "firewall-all-allow-ssh" {
```
Comment (paseaf) [inline terraform/main.tf:27]:
```suggestion
resource "google_compute_firewall" "firewall_all_allow_ssh" {
```
convention

File: terraform/main.tf [hunk 3]
```diff
@@ -23,41 +23,68 @@ resource "google_compute_subnetwork" "honeypot_subnet" {
...
+  source_tags = [ "gateway" ]
+  target_tags = [ "sacrificial" ]
+  allow {
+    protocol = "tcp"
+    ports = [ "2376" ]
+  }
+}
+
+# close all outgoing connection from sacrificial host
+resource "google_compute_firewall" "firewall-sacrificial-no-egress" {
```
Comment (paseaf) [inline terraform/main.tf:69]: same

**Review by paseaf — COMMENTED** [review]
some TODOs for us:
- clean up what needs to be cleaned
- try to automate everything
- finish the whole setup
- add some description to the PR if needed

File: packer/main.pkr.hcl [hunk 4]
```diff
@@ -8,61 +8,104 @@ packer {
 }
 
 source "googlecompute" "ubuntu-2204" {
-  project_id          = "containerssh"
+  project_id          = var.project_id
```
Comment (bafread) [inline packer/main.pkr.hcl:11]: implement a variable instead of using the project ID directly

File: packer/main.pkr.hcl [hunk 5]
```diff
@@ -8,61 +8,104 @@ packer {
...
   source_image_family = "ubuntu-pro-2204-lts"
   ssh_username        = "root"
   zone                = "europe-west3-c"
   account_file        = "./gcp.key.json"
+  machine_type        = "e2-small"
```
Comment (bafread) [inline packer/main.pkr.hcl:16]: cost minimization (maybe)

File: packer/variables.pkr.hcl [hunk 6]
```diff
@@ -0,0 +1,11 @@
+//  variables.pkr.hcl
+
+// For those variables that you don't provide a default for, you must
+// set them from the command line, a var-file, or the environment.
+
+variable "project_id" {
+  type =  string
+  default = "containerssh-352007"
```
Comment (bafread) [inline packer/variables.pkr.hcl:8]: Enter your project ID here

File: terraform/main.tf [hunk 7]
```diff
@@ -23,41 +23,80 @@ resource "google_compute_subnetwork" "honeypot_subnet" {
...
   network = google_compute_network.main.self_link
 
   allow {
     protocol = "icmp"
   }
-
   allow {
     protocol = "tcp"
-    ports    = ["22", "9091"]
+    ports    = ["22"]
```
Comment (bafread) [inline terraform/main.tf:36]: Open port 22 for all VM (for SSH), so that it's easier to control
TODO Later: open port 22 **only** for gateway-vm

File: terraform/main.tf [hunk 8]
```diff
@@ -23,41 +23,80 @@ resource "google_compute_subnetwork" "honeypot_subnet" {
...
 
+# open port 9090 and 9091 on our logger-vm: to control metrics and minio
+resource "google_compute_firewall" "firewall_logger_view" {
+  name    = "firewall-logger-view"
+  network = google_compute_network.main.self_link
+  allow {
+    protocol = "tcp"
+    ports    = ["9090", "9091"]
+  }
+  target_tags = [ "observer" ]
```
Comment (bafread) [inline terraform/main.tf:49]: Open port 9090 and 9091 for Observer, so we can have access on MinIO and  Prometheus

File: terraform/main.tf [hunk 9]
```diff
@@ -23,41 +23,80 @@ resource "google_compute_subnetwork" "honeypot_subnet" {
...
   source_ranges = ["0.0.0.0/0"]
 }
 
-resource "google_compute_firewall" "allow_node_exporter_e" {
-  name    = "allow-node-exporter-e"
+# open gateway-port 9100 and 9101, to our prometheus and metrics server
+resource "google_compute_firewall" "firewall_gateway_nodeexport" {
+  name    = "firewall-gateway-nodeexport"
```
Comment (bafread) [inline terraform/main.tf:55]: Name-Conversion

File: terraform/main.tf [hunk 10]
```diff
@@ -23,41 +23,80 @@ resource "google_compute_subnetwork" "honeypot_subnet" {
...
+  allow {
+    protocol = "tcp"
+    ports = [ "2376" ]
   }
+}
 
-  source_ranges = ["10.0.0.0/24"]
+# close all outgoing connection from sacrificial host
+resource "google_compute_firewall" "firewall_sacrificial_no_egress" {
+  name = "firewall-sacrificial-no-egress"
```
Comment (bafread) [inline terraform/main.tf:82]: Name-Conversion

File: terraform/main.tf [hunk 11]
```diff
@@ -78,16 +117,18 @@ resource "google_compute_instance" "gateway_vm" {
 
   provisioner "remote-exec" {
     scripts = [
+      "./scripts/setup_ca.sh",
       "./scripts/download_node_exporter.sh",
-      "./scripts/run_node_exporter.sh"
+      "./scripts/run_node_exporter.sh",
+      "./scripts/run_docker_container.sh"
```
Comment (bafread) [inline terraform/main.tf:123]: as per Janos's suggestion, running container inside gateway-vm to run sshcontainer

File: terraform/scripts/run_docker_container.sh [hunk 12]
```diff
@@ -0,0 +1,12 @@
...
+set -euxo pipefail
+
+export DEBIAN_FRONTEND=noninteractive
+
+# source: https://devopscube.com/run-docker-in-docker/
+sudo docker run -dit \
+   --name docker_container \
+   -v /var/run/docker.sock:/var/run/docker.sock \
+   -v /srv/containerssh/:/srv/containerssh/ \
+   docker
```
Comment (bafread) [inline terraform/scripts/run_docker_container.sh:12]: script to run docker inside docker

File: packer/README.md [hunk 13]
```diff
@@ -30,7 +30,7 @@ What you need:
 
    > Note: if you want to use a different file name or location, change `account_file` in [`./main.pkr.hcl`](./main.pkr.hcl) accordingly
 
-3. Update `project-id` in `main.pkr.hcl` to match yours
+3. Update `project-id` in `variables.pkr.hcl` to match yours
```
Comment (bafread) [inline packer/README.md:33]: Update readme file to match the changes

File: packer/scripts/update.sh (hunk 1 above)
[the remark this answers is not in the document]
Comment (paseaf) [reply packer/scripts/update.sh]: Just changed it back to `reboot` as it's much faster and works now... (I tested it for > 10 times)
(maybe because of 
```diff
  provisioner "shell" {
    script            = "./scripts/update_apt_packages.sh"
+    expect_disconnect = true
  }
```

File: terraform/main.tf (hunk 7 above)
Comment (paseaf) [reply terraform/main.tf:36]: We can finalize firewall rules in #5 after everything works

File: terraform/scripts/run_docker_container.sh (hunk 12 above)
Comment (paseaf) [reply terraform/scripts/run_docker_container.sh]: will check it in later steps

File: packer/main.pkr.hcl [hunk 14]
```diff
@@ -17,52 +17,91 @@ source "googlecompute" "ubuntu-2204" {
...
   }
 
+  provisioner "file" {
+    source      = "./scripts/util_fn"
+    destination = "/home/tmp/util_fn"
+  }
   provisioner "shell" {
-    script = "./scripts/update.sh"
+    script            = "./scripts/update.sh"
+    expect_disconnect = true
```
[the remark this answers is not in the document]
Comment (paseaf) [reply packer/main.pkr.hcl:44]: works great!

**Review by paseaf — APPROVED** [review]
Finished CA set up with manual configuration.
Will do next steps in future PRs.

### TODOs before merge:
- [ ] check out answers to open questions and update our code if needed
- [ ] remove `ca*.tar` files and relevant config
- [ ] verify CA set up again with readme

File: packer/main.pkr.hcl [hunk 15]
```diff
@@ -8,61 +8,106 @@ packer {
...
+  provisioner "shell" {
+    inline = [
+      "mkdir -p /home/deployer/tmp",
+    ]
+  }
+
+  # test
+  provisioner "file" {
+    source      = "./files/ca_client.tar"
+    destination = "/home/deployer/tmp/ca_client.tar"
```
Comment (paseaf) [inline packer/main.pkr.hcl:77]: We probably shouldn't commit these files for security.
Will remove relevant parts and  use for manual configuration now.

We could automate it later using Ansible

Comment (paseaf) [reply packer/main.pkr.hcl]: removed
