### PR TITLE
fix: dockerd has too low nofile limit on sacrificial VM

### LINKED ISSUE #51: `dockerd` on Sacrificial VM stopped running after a while
## Current behavior: `dockerd` stopped responding
`dockerd` logs
```
2022-07-24 04:48:35.375843 I | http: Accept error: accept tcp [::]:2376: accept4: too many open files; retrying in 1s
2022-07-24 04:48:35.613364 I | http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
2022-07-24 04:48:36.376390 I | http: Accept error: accept tcp [::]:2376: accept4: too many open files; retrying in 1s
2022-07-24 04:48:36.613764 I | http: Accept error: accept unix /var/run/docker.sock: accept4: too many open files; retrying in 1s
```

ContainerSSH logs
> "The backend has rejected the user after successful authentication. (failed to create container, giving up (Cannot connect to the Docker daemon at tcp://sacrificial-vm:2376. Is the docker daemon running?))"

## Investigation
**Possible reason: too low default `nofile` (#open files limit) for `dockerd`.**
Details: https://github.com/paseaf/ContainerSSH-honeypot/issues/51#issuecomment-1193271988

**Possible solution: start `dockerd` with a higher `nofile` limit**
Details: https://github.com/paseaf/ContainerSSH-honeypot/issues/51#issuecomment-1193279149

## TODOs
- [x] find a solution
- [x] monitor the solution
- [ ] update deployment scripts and README with the solution.

### PR DESCRIPTION
**Pull request by paseaf**
This PR should
- fix #51 

  1. `terraform apply`
  2. `gcloud compute ssh root@sacrificial-vm`, then `cat /proc/$(pidof dockerd)/limits | grep "Max open files"`. You should see both values larger than 65565.
  3. ssh into the honeypot 10 times at the same time. they should all work

## Takeaways
Written in the issue comments.

### CODE REVIEW

File: terraform/scripts/restart_dockerd_with_tls.sh [hunk 1]
```diff
@@ -3,14 +3,22 @@ set -euxo pipefail
...
-   -H=0.0.0.0:2376 \
-   &> dockerd.log &
+
+TARGET_DIR=/lib/systemd/system/docker.service.d
+mkdir -p "$TARGET_DIR"
+
+# override default ExecStart
+cat > "$TARGET_DIR/local.conf" << EOF
+[Service]
+ExecStart=
```
Comment (paseaf) [inline terraform/scripts/restart_dockerd_with_tls.sh:13]: to clean up existing `Execstart`
